version: '3.7'

services:
    app:
        build: starwars
        restart: ${RESTART:-no}
        volumes:
            - ./:/app
        working_dir: /app/starwars
        ports:
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        command: ${RUNSERVER:-/bin/bash}
