version: '3.7'

services:
    app:
        build: starwars
        restart: ${RESTART:-no}
        volumes:
            - ./:/app
        working_dir: /app/starwars
        ports:
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        command: ${RUNSERVER:-/bin/bash}
        networks:
            - nginx-gateway
        environment:
            VIRTUAL_HOST: valora.lfvilella.com
            VIRTUAL_HOST_ALIAS: valora.lfvilella.com,www.valora.lfvilella.com
            LETSENCRYPT_HOST: valora.lfvilella.com,www.valora.lfvilella.com
            LETSENCRYPT_EMAIL: vilella.luisfelipe+valora.lfvilella.com@gmail.com

networks:
    nginx-gateway:
        external:
            name: nginx-gateway
